# Generated by Django 3.2 on 2023-08-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20230828_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[('US', 'user'), ('AD', 'admin'), ('MO', 'moderator')],
                default='US',
                max_length=2,
            ),
        ),
    ]
