# Generated by Django 3.2 on 2023-08-28 20:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230828_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        regex='^[\\w.@+-]+\\Z'
                    )
                ],
            ),
        ),
    ]
