# Generated by Django 3.2 on 2023-08-28 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[('US', 'User'), ('AD', 'Admin'), ('MO', 'Moderator')],
                default='US',
                max_length=2,
            ),
        ),
    ]
