# Generated by Django 3.2 on 2023-08-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('user', 'User'),
                    ('admin', 'Admin'),
                    ('moderator', 'Moderator'),
                ],
                default='user',
                max_length=10,
            ),
        ),
    ]
