# Generated by Django 3.2 on 2023-09-03 12:20

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20230903_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(
                validators=[reviews.validators.validate_year]
            ),
        ),
    ]
